### PR TITLE
Changed lodash version to ~2.4.1

### PR DESCRIPTION
**Pull request by grommett**
Should resolve issues:
https://github.com/saucelabs/docs/issues/107
https://github.com/saucelabs/docs/issues/110
https://github.com/saucelabs/grunt-init-sauce/issues/3

### CODE REVIEW

**Comment by Jonahss** [comment]
Thanks!
We've got a task to update and tidy-up the entire module (we should be on the latest version of dependencies) but this will fix us up for now.

**Comment by Jonahss** [comment]
Thanks @grommett , can I offer you some minutes added to your account on Sauce Labs?

**Comment by grommett** [comment]
@Jonahss You're welcome. That would be much appreciated!

**Comment by Jonahss** [comment]
Sure, send me an email with your account username: jonahss@saucelabs.com

**Pull request merged**
